language: node_js
node_js: 6.3.0
sudo: false
script:
- echo Hello,World!
after_success:
- '[ "$TRAVIS_BRANCH" == "source" ] && npm run deploy'
notifications:
  slack:
    secure: dK1nkyxjQq6W0x5WmgZ6iFbMb9yqZlCDq+ybuvR7bvzax3UDddGfA+EbnLX6c4Xrp6Z0Lb2gN35GFngv0iTu1CCX4YXSueyzO2clEosK5RUwMnl4tgylpycPucfgeL7OwKm+RU/1DvY2ylKkiCMA/+HKJf2lqCyaVvygImvauzf8DraDxXLP5tVfk9BvBNT+JH5fYiqGWy6fCrKMDG6P/qnXC5nT8WtD9psP6ul1XKmK5oYxxs+9Insj5hLRu+QLrfu4CVCsP3sYNth97NJ1sE/hsLiuaMxJjJ7GLWeBzDIPWD5Jr99AY1ueWdEJhotzydHKjiELgo5yeRuNeIVgVT+tjnF3yXPsXY7Lj8uSEFjjQUcK/Uskqgm1Bey8+kXl53IB00WILobBwth0kJinPsfYUKCtaqXslT5VvT5/dPCP3CTQnddkJbKSKVHkhgB2pV4zScBrEln2zmStTiIbqe6k+sv1LdyaHEApTAKBt8bMcketBpcJWzOWO+7OQx/cOVCO+gzUFFPLsLXxuWn4fIvAqrR0HyD8SO0O7ht5MZNXB3tD0JSe2DYpD9qyEAfWz7FBYpJr3hamBjQmSePYBarotfgEBbkik04NTdZrfNQg146XTJz0BNUl3ly5lnUMzBK1XvPpS/31kpEjMQLaNA/so3FwFFNAD4vXe9Bf2Io=
